version: '3.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esvol:/tmp
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
    ports:
      - 9200:9200
  python_client:
    build: './python_client'
    container_name: python_client
    volumes:
      - ${HOME}/data:/data
    ports:
      - 8888:8888
    networks:
      - esnet
    depends_on:
      - elasticsearch
    restart: on-failure
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch
networks:
  esnet:
volumes:
  esvol: